# Generated by Django 4.2.8 on 2023-12-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='car_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('FIELDNAME', models.SlugField(unique=True)),
                ('year', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('price', models.FloatField()),
                ('promo_price', models.FloatField(blank=True, null=True)),
                ('car_photo', models.ImageField(upload_to='car_photo')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
