# Generated by Django 4.2.8 on 2023-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_fieldname_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Register',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
