# Generated by Django 4.2.8 on 2023-12-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customer_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_registration',
            name='username',
        ),
    ]
