# Generated by Django 4.2.8 on 2023-12-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_customer_registration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_registration',
            name='username',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
