# Generated by Django 4.2.8 on 2023-12-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customer_registration_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_registration',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
