# Generated by Django 4.2.8 on 2023-12-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customer_registration_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.IntegerField()),
            ],
        ),
    ]
