# Generated by Django 4.2.8 on 2024-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='additional_info',
            field=models.TextField(default='a'),
        ),
    ]
