# Generated by Django 4.2.8 on 2024-02-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_payment_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='additional_info',
            field=models.TextField(),
        ),
    ]
