# Generated by Django 4.2.8 on 2024-02-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_payment_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='phone',
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='080', max_length=50),
        ),
    ]
