# Generated by Django 4.2.8 on 2024-03-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_manual_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car_product',
            field=models.CharField(default='toyota', max_length=50),
        ),
    ]
